export const SEARCH_FOCUES = "search_focues"
export const SEARCH_BLUR = "search_blur"
export const CHNAGE_LIST = "change_list"
export const GET_MOUSE_ENTER = "GET_MOUSE_ENTER"
export const GET_MOUSE_LEAVE = "GET_MOUSE_LEAVE"
export const CHNAGE_PAGE = "CHNAGE_PAGE"